### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [andrewkroh/google-oidc-auth-middleware#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to load readme: failed to get the readme file: GET https://api.github.com/repos/andrewkroh/google-oidc-auth-middleware/readme?ref=v0.0.1: 404 Not Found []
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by andrewkroh** [comment]
Add at https://github.com/andrewkroh/google-oidc-auth-middleware/blob/main/README.md
